name: Eureka DevSecOps GitHub Action Scans

on:
  workflow_dispatch:
  pull_request:
    branches:
        - master
  push:
    branches:
        - '*'

jobs:
  eureka-devsecops-scan:
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: npm install && npm i --package-lock-only
        
      - name: Run Eureka DevSecOps GitHub Action Scan
        uses: FWDSEC/eureka-scan-action@refactor-gh-action
        with:
          tag: 'staging'
          custom_eureka_vdbe_url: 'https://vulns.staging.eurekadevsecops.com'
          
        env:
          EUREKA_AGENT_TOKEN: ${{ secrets.EUREKA_AGENT_TOKEN }}
          EUREKA_PROFILE_ID: ${{ secrets.EUREKA_PROFILE_ID }}
