name: Radar CLI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ master ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: eurekadevsecops/scan-action@v2
        with:
          scanners: gitleaks,opengrep,grype
          token: ${{ secrets.EUREKA_AGENT_TOKEN }}
